name = "OnlineScenarioOptimization"
uuid = "503a5544-efba-463d-8c84-eb69f36fa127"
authors = ["guberger <guillaume.berger@colorado.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Distributions = "0.25.116"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
SpecialFunctions = "2.5.0"
Test = "1.11.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
